### ISSUE TITLE
The legacy (0.x) documentation website: Invalid SSL certificate

### ISSUE THREAD

**Issue by aakhundov** [polyaxon/polyaxon#1123]
### Describe the bug

The legacy documentation website https://legacy-docs.polyaxon.com is showing `Error 526 "Invalid SSL certificate"`.

### To reproduce

Open https://legacy-docs.polyaxon.com.

### Expected behavior

The website working properly again.

**Comment by mouradmourafiq** [comment]
We pushed a notification banner about some security issues, seems it broke the build.
We will fix the issue (upgrade the breaking packges), in the meantime you can access all documentation guide via github: https://github.com/polyaxon/polyaxon/tree/0.6.1/docs

Sorry about that.

**Comment by mouradmourafiq** [comment]
I spent 3 hours this weekend to fix the issue, the problem comes from this library https://github.com/kornelski/pngquant, upgrading the library breaks 14 other npm packages.

I think we should just announce that we will not maintain Polyaxon v0 anymore, the project itself has several outdated libraries, some of them have security issues and vulnerabilities, to update Polyaxon with newer versions of these packages and resolve any changes will require more or less a week worth of time.

I would suggest that you deploy Polyaxon v0 in protected networks only, you can keep viewing the docs via github or on your local machine if you pull the repo, the project and docs are open-source under Apache 2 license.

**Comment by aakhundov** [comment]
@mouradmourafiq thank you for your efforts.

Do I get it right, that https://legacy-docs.polyaxon.com won't be available anymore (as it is not at the moment)? And, if so, could you please advise on which rendering engine may be used to build the docs similarly to how they used to be accessible at https://legacy-docs.polyaxon.com: i.e., searchable, with nested table of contents, etc?

**Comment by mouradmourafiq** [comment]
There are several other projects that can consume markdown, [Mkdocs](https://www.mkdocs.org/) is a good option. You will probably need to customize the files to enable some features.

**Comment by DhDeepLIT** [comment]
Same problem here..

You can run something like :

`#!/bin/bash

TGT=mkdocs.yml
touch $TGT
DOC_DIR=docs

echo "site_name: Polyaxon_0.61" > $TGT
echo "nav: " >> $TGT

for rep in ${DOC_DIR}/*; do
    if test -d $rep; then
	echo "- "`basename $rep`":" >>$TGT;
	for fich in $rep/*; do
	    echo -e "   - ${fich}" | sed s/"docs\/"//g >> $TGT;
	done ;
    fi;
done

echo "theme: readthedocs" >> $TGT
echo "docs_dir: docs " >> $TGT`

and then do a 
mkdocs serve -a 0.0.0.0:8000

from the 0.61 root folder but some images are missing ...

**Comment by aakhundov** [comment]
@DhDeepLIT thanks for the tip!

@mouradmourafiq is there a chance we can get the images from the `content/images` folder?

**Comment by mouradmourafiq** [comment]
@aakhundov I don't think we have the right to distribute some assets with an open-source license.
