### ISSUE TITLE
Errors starting up on Google Kubernetes Engine

### ISSUE THREAD

**Issue by honnibal** [polyaxon/polyaxon#114]
Thanks for your work on this. I'm new to Kubernetes so I'm just having some trouble getting set up.

I'm using Google Kubernetes Engine. At first I launched the cluster without auto-scaling, which seemed to be responsible for pods failing to launch --- it defaulted to max 3 nodes, which I guess is too few? I then set autoscaling to true and set 8 max nodes.

However, I'm still not starting everything correctly:

```
$ kubectl --namespace=polyaxon get pod
NAME                                                   READY     STATUS             RE
polyaxon-docker-registry-6d84bc56c6-qh959              1/1       Running            0 
polyaxon-polyaxon-api-6b498cf98c-28r68                 1/2       CrashLoopBackOff   5 
polyaxon-polyaxon-beat-6f57845d8b-twnpc                2/2       Running            0 
polyaxon-polyaxon-events-76cd7dcfcd-gdbr7              2/2       Running            3 
polyaxon-polyaxon-http-backend-796449b566-8rzks        1/1       Running            0 
polyaxon-polyaxon-ingress-controller-78f6f7b44-9jfqq   1/1       Running            0 
polyaxon-polyaxon-resources-6r6bl                      1/1       Running            3 
polyaxon-polyaxon-resources-7gghd                      1/1       Running            1 
polyaxon-polyaxon-resources-jpltv                      1/1       Running            1 
polyaxon-polyaxon-resources-vmp7d                      1/1       Running            1 
polyaxon-polyaxon-resources-vsm8l                      1/1       Running            3 
polyaxon-polyaxon-scheduler-6f7c57bf6-bndbz            0/1       CrashLoopBackOff   5 
polyaxon-polyaxon-workers-77658d9cb4-7mcwg             0/1       CrashLoopBackOff   5 
polyaxon-postgresql-66f79594fd-x2jjt                   1/1       Running            0 
polyaxon-rabbitmq-6945cfcb7f-m9rg5                     1/1       Running            0 
polyaxon-redis-6c767f7f99-cpsfm                        1/1       Running            0  
```

I'm having trouble finding useful error logs in GKE. How do I figure out why the services won't start?

**Comment by mouradmourafiq** [comment]
Hi @honnibal the problem is not autoscaling, but it was the `/data`, `/outputs`, `/logs` paths. By default, if the user does not provide PVC, Polyaxon uses host nodes to create these paths.

2 problems are occurring, 
 * Kubernetes does not seem to be able to create these paths for permissions reasons
 * Since you are deploying a multi-node cluster, data and outputs should be ideally in a central volume.

I am going to create a tutorial on how to deploy on GKE, with 2 options:
 * single node which should work out of the box with default values
 * multi-node with `ReadWriteMany` PVC based on NFS.

The tutorial will be up ready tomorrow.

sorry for the confusion, I guess the documentation is not completely clear.

**Comment by honnibal** [comment]
Thanks! I'll probably make a terraform script to set up the file server. If I get something repeatable I'll share it here :)

**Comment by honnibal** [comment]
Did the tutorial, now it's waiting on the containers. I just enabled container registry now, so maybe that's an extra dependency I was missing?
