### ISSUE TITLE
How does the container caching work during build_steps?

### ISSUE THREAD

**Issue by honnibal** [polyaxon/polyaxon#120]
I'm not sure that this is the problem, but I suspect I'm getting stale containers when I'm modifying my scripts and rerunning the experiment.

If I understand correctly, each command during build_steps is run as a separate Docker RUN statement, right? And then Docker caches the result of that? If I rerun another experiment, it seems this uses the same cache, which can definitely be good. On the other hand, I've been having some problems that make me suspect the cache isn't being invalidated correctly.

Where are the containers cached to, during the build_steps process? I'd like to try flushing that cache to see if I can figure out the problem.

**Comment by mouradmourafiq** [comment]
Which Polyaxon version are you using?

**Comment by mouradmourafiq** [comment]
`helm list | grep polyaxon`
`polyaxon version --platform`

**Comment by honnibal** [comment]
```
polyaxon        1               Wed May 16 01:43:32 2018        DEPLOYED        polyaxon-0.0.8  polyaxon 

$ polyaxon version --platform

Current platform version: 0.0.8.                                                                  
                                                                                                  

Supported platform versions:                                                                      
                                                                                                  
--------------  -----
latest_version  0.0.8
min_version     0.0.8
--------------  -----
```

**Comment by mouradmourafiq** [comment]
It's a bug related to concurrent builds, it was fixed in the latest version 0.0.9. It's a bit annoying right now because you need to kill these experiments manually, especially if you are using iterative search algorithms because these algorithms depend on all experiments in the iteration to finish before making new suggestions.

If you want to update the deployment to the new version, you need to run:
1 . `helm update`
2. `helm upgrade polyaxon polyaxon/polyaxon -f your_config.yaml`
3.  optionally `pip install -U polyaxon-cli`

Hopefully the upgrade will go through without problems.

**Comment by honnibal** [comment]
I can just purge the installation and clean install right? I haven't done anything important.

**Comment by mouradmourafiq** [comment]
Yes, you can do that as well, just remember to do `helm update` before installing.
