### ISSUE TITLE
Reuse connections for uploading/downloading/streaming artifacts

### ISSUE THREAD

**Issue by mouradmourafiq** [polyaxon/polyaxon#1249]
### Current behavior

I think the sidecar reinitializes a new client connections to sync artifacts to S3/GCS/Azure.

### Enhancement

Only re-initialize the connection on errors and reuse the same client during the complete session.

**Comment by lgeiger** [comment]
I am currently running into this issue when using [`tf.keras.callbacks.experimental.BackupAndRestore`](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/experimental/BackupAndRestore) which continuously stores checkpoints of the format `backup/chief/ckpt-{epoch}.index` every epoch to allow for automatic resuming after machine failure. This callback will automatically cleanup old checkpoints after each epoch and fully remove the directory after training has been completed. This cleanup is quite important since the checkpoints can easily take up many GB of storage.

Previously we wrote the checkpoints and all output directly to GCS instead of relying on Polyaxon to handle syncing.
What is the recommended usage with Polyaxon v1? Is it better to rely on Polyaxon to sync the output directories or should user code directly write to GCS?
Writing directly to GCS is easy to do with TensorFlow since GCS is automatically supported via [`tf.io.gfile`](https://www.tensorflow.org/api_docs/python/tf/io/gfile), but I am not sure if Polyaxon handles it correctly when some parts of the user code write directly to the underlying storage while others rely on the sidecar to do the syncing.
