### ISSUE TITLE
Logs viewer scrollbar allows for horizontal scolling of logs container

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#1270]
### Describe the bug

The current design disables horizontal scrolling of logs in favour of an expand button. However, when vertical scrolling is required the scrollbar breaks the CSS and allows for horizontal scrolling of the logs container which hides the expand button.

### To reproduce

https://user-images.githubusercontent.com/13285808/114221955-42236400-996e-11eb-92af-5201f68e3afd.mov

### Expected behavior

Then logs viewer should not scroll horizontally when a vertical scrollbar is present, or the expand button should be disabled in favour of proper horizontal scrolling (I think I would prefer the former option).

### Environment
Polyaxon 1.8.0
Chrome 89
macOS 10.15

**Comment by mouradmourafiq** [comment]
This is an issue in the underlying library, it was fixed, and it's browser specific (I believe the issue is not present on firefox).
Unfortunately the PR for upgrading to the latest version and updating several changes (including virtualization) was not merged again, so it's tentatively pushed to v1.9 (https://polyaxon.com/docs/releases/1-9/#ui)

**Comment by lgeiger** [comment]
Makes sense. I can confirm that this issue is not present on Firefox 👍
