### ISSUE TITLE
Problems with the 'Download CSV' functionality.

### ISSUE THREAD

**Issue by AdamHillier** [polyaxon/polyaxon#1281]
### Describe the bug

Above a list of jobs, there's a 'Download CSV' button (next to the 'Visualise' button). Clicking it brings up this interface:

![image](https://user-images.githubusercontent.com/7688302/114850748-fee74c00-9dd8-11eb-8b53-cff64fe2952b.png)

There are two problems:
  1. The 'Selection' drop-down offers only one option ("Current page"). There's no option to select "Whole list". Unfortunately, because of list pagination this is a problem. "Rows per page" has a maximum value of 50, which means you can only download CSV data on a maximum of 50 runs at a time. If I have a list of jobs (e.g. from a big grid search) with more than 50 rows I have to go through each paginated page and download multiple CSVs, and stitch them all together by hand afterwards.
  2. The 'Columns' drop-down offers the option "All columns", where it includes currently hidden columns. At least for the particular list of jobs I'm wanting to download CSV data for, when I select "All columns" the download button then doesn't work. In the browser console, after clicking the download button, I see a JS error of the following form (apologies, this isn't very illuminating because of JS minification):<br><br><img width="355" alt="image" src="https://user-images.githubusercontent.com/7688302/114851583-e7f52980-9dd9-11eb-8e5c-b20d41226fbc.png">

### To reproduce

Problem 1. can be reproduced by trying to download a CSV file for all the jobs in a matrix, where the total number of jobs > 50. Problem 2. might be hard to reproduce, I'm not sure. It seems that certain data in certain columns causes a problem in the front-end JS code.

### Expected behavior

1. It should be easy to download a CSV file containing all rows in one go.
2. It shouldn't be possible for malformed data in a column to break the CSV download functionality.

### Environment

Back-end: Polyaxon v1.8.2.
Front-end: MacOS, on the latest versions of both Firefox and Safari.

**Comment by polyaxon-team** [comment]
The selection dropdown is only enabled when the user has a selection in the table, it offers: `current selection vs current page`.
The feature for selecting data from the API directly is not implemented yet, that's a UI limitation at the moment. But in the short term, with virtualization, the table will have higher page sizes, and we could possibly allow downloading a CSV based on the full query specification.

For now you can do similar logic in the CLI: `polyaxon ops ls -io --to-csv --limit=1000 -p PROJECT_NAME`, since you mentioned a grid search, you can also add the `-q pipeline: UUID_OF_THE_GRID_PIPELINE`, and you can also supplment the sort, limit, and offset, please check `polyaxon ops ls --help`.

For probelm 2, we will do some testing. Thank for sharing the console error.

**Comment by AdamHillier** [comment]
> For now you can do similar logic in the CLI: `polyaxon ops ls -io --to-csv --limit=1000 -p PROJECT_NAME`, since you mentioned a grid search, you can also add the `-q pipeline: UUID_OF_THE_GRID_PIPELINE`, and you can also supplment the sort, limit, and offset, please check `polyaxon ops ls --help`.

Thanks for the quick response! This indeed works perfectly for my use case, thank you.

**Comment by mouradmourafiq** [comment]
> 2. It shouldn't be possible for malformed data in a column to break the CSV download functionality.

This was fixed, and it's live.
