### ISSUE TITLE
Dockerizer - image builder

### ISSUE THREAD

**Issue by engapa** [polyaxon/polyaxon#172]
Anybody knows how to build docker images by Dockerfiles, and the actual "builder" uses an internal jinja template that I think is insufficient (note that only certain resources are available for RUN steps, i mean requirements.txt, or setup.sh, and something more).

Three purposes:
 - A key **build.dockerfile** entry in polyaxonfile.yml to import existing Dockerfile (and aligning with well known docker-compose files, and with .dockerignore file we can hide files to docker build process)
 - An entry **build.template** to use a custom jinja template (using prebuilt jinja polyaxon templates/macros, for instance)
 - Allow all resources of repo are available in building image time, for all build_steps (`RUN` commands). When in jinja template appears the command `COPY build/[*] /code/[*]` (where * are only certain resources as I said above) change that for `ADD . .` (remind .polyaxonignore and .dockerignore files)

**Comment by mouradmourafiq** [comment]
The first point allowing to use a dockefile is related to this issue #154.

I am also wondering if pre-backing docker images would be helpful in this case, if you need some base image, and only use Polyaxon image building for light operation. In any case I am very open to this.

For the `.dockerfileignore`: I think you have a point there, polyaxon should probably allow this, although  it's possible to use the `.polyaxonignore` to avoid uploading some files, but I can see that in some cases this could be limiting.

For the **build.template** I think I did not get that,  can you provide a usecase.

I think that allowing the user to use a dockerfile should be sufficient to do advance use cases, instead of exposing all advanced docker commands.

**Comment by cBournhonesque** [comment]
I agree that it would be super useful to have access to the code in /build during the build_steps process. It's kind of unsufficient to only have access to requirements.txt and polyaxon_setup.sh

**Comment by rapatel0** [comment]
A custom Jinja template would actually go a long way to simplify security concerns. At deployment time, we can enforce certain users to be available within the container and prevent root access to the host

**Comment by rapatel0** [comment]
I just wanted to clarify my comment a bit. I think that having a custom Jinja template would be useful at deployment time as opposed to run time. The issue I have at the moment is that through this process we expose root level access to the cluster within every polyaxon job. This is problematic on several levels. Ideally, We would like to change the Jinja template, to run as a specific user that is pulled from a password file or ldap. We could install these as part of our deployment and have validated images from our private registry.

**Comment by mouradmourafiq** [comment]
Let's chat on slack, I am in the process of refactoring the build process to have:
 * a native builder
 * kaniko
 * other plugins that the user might want to deploy

**Comment by mouradmourafiq** [comment]
Closing this as the next release will introduce an option to use own dockerfile instead of the generated one.
