### ISSUE TITLE
Missing stderr from build logs?

### ISSUE THREAD

**Issue by honnibal** [polyaxon/polyaxon#181]
Hi Mourad,

It looks like the stderr is missing from the build logs -- I'm only seeing the stdout output. This makes debugging a bit tricky.

Btw, it's really cool that v0.2.2 now exposes the Dockerfile...Makes the build much easier to debug locally. I wonder whether it might be better to have an option to use a local dockerfile directly, instead of specifying the build steps within the polyaxonfile? Having code in the yaml is sort of awkward, as it's hard to test the code independently of Polyaxon.

**Comment by mouradmourafiq** [comment]
Hi Matt, 

There are a couple of things that were fixed regarding logs/errors in dev branch, the changes will be part of the 0.3 version:
 1. issues related to exceptions raised by the docker api: the stack trace will be available on the `failed` status since this error is generally raised before starting the build and creating the pod.
 2. issues related to build getting deleted quickly from k8s and hence no logs available.
 3. An option: `--ttl`  for the run command to keep the k8s resources available for the user to debug.

The second part: "possibility to provide a dockerfile" is on the roadmap, there are already 2 similar github issues. It's also planned for the 0.3, but it's not done yet.

**Comment by honnibal** [comment]
Sweet, thanks :tada:
