### ISSUE TITLE
Advice for scaling up?

### ISSUE THREAD

**Issue by honnibal** [polyaxon/polyaxon#183]
My experiments can run on small CPU instances, so I can afford to search deeply for hyper-parameters. When I run more than about 100 concurrent experiments, eventually the API becomes unresponsive, and the dashboard basically crashes. Everything looks healthy on the dashboard on GKE, so I'm not sure exactly what's wrong.

Should I give the API more resources? Or ideally replicas? I've tried to do both, but I'm doing something wrong, as the pods won't start when I change these settings. Alternatively, I'd be happy to help make the API more efficient, if I could figure out where it's dying.

**Comment by honnibal** [comment]
Tentatively, my guess is that when there are too many unschedulable pods, the API gets hammered and the dashboard becomes unresponsive?

**Comment by mouradmourafiq** [comment]
I will update this issue later today with a config. 

In general a 100 parallel jobs is rarely an issue, you might see issues with 1000, but also with the right configuration that's not an issue as well. 

The issue you are seeing could be related to either memory or cpu, or both, the default config allows the pods to consume more resources if they need them, unless you enbale `limitResources`, but if the experiment jobs are scheduled on the same node as Polyaxon components, this could be an issue.

The only use for the api during the scheduling of jobs is reporting metrics, which would be throttled by the API if it's an issue.

**Comment by honnibal** [comment]
Thanks. This is how I'm launching the cluster currently:

```
gcloud beta container --project "gpu-compute-project" clusters create "polyaxon-test" --zone "europe-west1-d" --username "admin" --machine-type "n1-standard-4" --image-type "COS" --disk-size "20" --network "default" --preemptible --enable-autorepair --enable-autoscaling --min-nodes=3 --max-nodes=100
```

**Comment by mouradmourafiq** [comment]
Sorry for the late answer.

I just want to share some ideas that could impact the responsivenece of the api and system in general. I just deployed a cluster on GKE. The cluster itself is not large, I have 24 nodes, and I am running more than 300 || experiments in different experiments groups with different concurrency settings.

The only difference that I think I have compare to your setting is probably the following, I have 3 pools: 

 * One pool I reserve it to the k8s system and I am also deploying the Polyaxon core components in it, this pool has 3 nodes `n1-standard-4 (4 vCPUs, 15 GB memory)`. In a production settings, especially if you have other apps deployed on k8s, you shoule always try to avoid deploying other things on the same node as the k8s system components.

 * One pool I reserved it to the experiments, in my case I just want to spin a large workloads without caring how long it will take to finish, so I opted for 20 nodes `n1-standard-2 (2 vCPUs, 7.5 GB memory)` the experiments will be slow but they won't have a chance to impact Polyaxon or the system.

 * One node for the builds, this pool in my case is just one node `n1-standard-4 (4 vCPUs, 15 GB memory)`. This could be a larger node depending on what you are building. Sometimes the builds will require large memory.

This is a very small setup and the api, statuses, metrics, and logs are tracked correctly. 

<img width="932" alt="screen shot 2018-09-22 at 00 30 19" src="https://user-images.githubusercontent.com/1261626/45908868-10be0980-bdff-11e8-87e0-b6bee6f80b7a.png">


Just to clarify this is not also an ideal solution, but it gives some ideas on how to structure a deployment. Most of the time when you don't use `node selectors` and other scheduling provided by the platform, deployments might end up having too many pods scheduled either on the same node as the k8s master node, which could make the cluster behave badly, or on the same node as the api, database, or rabbitmq, and they could eat all memory/cpu.

There are also a couple of ideas that I would really like to find some time to implemet, and I am they will speed the platform a lot, but I need to work both on features and improvements :), so I am doing that incrementally.

One last thing, I think I introduced a regression a couple of weeks ago, and some of the validations of the cluster's events is not done correctly, that's why somwtimes you might see experiments getting stuck in the scheduled state, other people have reported that as well, and I hope that I will make a fix this weekend.

Let me know if you need anything else, I am happy to help.

**Comment by mouradmourafiq** [comment]
I forgot to mention that replication is also possible and could be useful in some instances even after tuning the deployment. Depending on the use case one or multiple services could be replicated, but the easiest way to replicate the platform is to increase the number of replicas of all services at once:

```yaml
api:
  replicas: 3

scheduler:
  replicas: 3

hpsearch:
  replicas: 3

eventsHandlers:
  replicas: 3

eventMonitors:
  replicas: 3
```
