### ISSUE TITLE
Make <TOKEN> as private variable in build section

### ISSUE THREAD

**Issue by vfdev-5** [polyaxon/polyaxon#286]
### Feature motivation
Following the discussion on slack
```
build:
build_steps:
  - apt-get -y update && apt-get -y install git vim curl
  - pip3 install --no-cache -U git+https://user:<TOKEN>@some-bitbucket-repo
```
Idea is to make <TOKEN> as private variable in order to not expose it in all experiment config files

**Comment by mouradmourafiq** [comment]
This should be part of next release 0.3.5.

**Comment by mouradmourafiq** [comment]
Although the scheduler now will pass any secret to the builder, the docker process will not be able to see the token, unfortunately. I think the only way, for now, is to build an intermediate base image to reuse later on by Polyaxon.

This can be fixed by providing richer docker interface for the build.

**Comment by joeyearsley** [comment]
Would it be possible to allow for external private git repos to be installed in a similar way to the use of `git:...`?
