### ISSUE TITLE
Support YAML file in a directory by passing the context path.

### ISSUE THREAD

**Issue by yu-iskw** [polyaxon/polyaxon#321]
### Feature motivation
From my understanding, we can put specification YAML files in a directory. We must place the files in the directory which is much closer to the root, such as `polyaxon-examples` and `polyaxon-quick-start`. However, I don't have many specification YAML files in the root. Instead, I want to put them in a nested directory.

I know that doesn't work righ now, since the building process with docker doesn't allow us to access to the parent directory and directories which are out of scoeps. The problem is not definitely essential, but many specification files in the project root looks messy to me.

```
.
├── polyaxon
│   └── polyaxon_job.yml
│   └── polyaxon_hyperparams.yml
│   └── polyaxon_hyperparams_bo.yml
├── src
│   └── __init__.py
│   └── download.py
│   └── train.py
└── setup.cfg
```

### Feature description
`docker build` enables us to specify the context path. So, We may be able to pass the context path to a specification YAML file as belo.

```{YAML}
build:
  image: my_image
  context: ..
  build_steps:
    - pip install PILLOW
    - pip install scikit-learn
```

**Comment by yu-iskw** [comment]
I understand that the directory of context depends on where `.polyaxon` is. If `.polyaxon` is placed appropriately, we can have nested YAML files.

```
.
├── .polyaxon
├── polyaxonfiles
│   └── polyaxon_job.yml
│   └── polyaxon_hyperparams.yml
│   └── polyaxon_hyperparams_bo.yml
├── src
│   └── __init__.py
│   └── download.py
│   └── train.py
└── setup.cfg
```

**Comment by mouradmourafiq** [comment]
Next release, v0.3.9, will introduce a couple of new features to customize the build:
 * Builds with kaniko as a backend (Beta)
 * build context: basically specifying which subpaths to mounts for the build
 * dockerfile: for users who want more control , instead of specifying the image, steps, ...
 * `polyaxon init` command will not create a polyaxonfile by default, i.e. new flag was created `--polyaxonfile` to generate the stub file, you can opt to put them wherever you want.

I am closing this, if you have further opinions after the release, you can open an new issue.

**Comment by yu-iskw** [comment]
I look forward to the next release!! Thanks!
