### ISSUE TITLE
Change Dockerfile image or to not run as root user. 

### ISSUE THREAD

**Issue by rapatel0** [polyaxon/polyaxon#323]
This should be trivial just add a polyaxon user and ensure that permissions are properly set in the container.

```
# Add user
ENV 	NB_USER polyaxon 
ENV 	NB_UID 999
ENV   NB_GROUP polyaxon
ENV   NB_GID 999

RUN   addgroup --gid $NB_GID $NB_GROUP    \
      && adduser --uid $NB_UID --shell /bin/bash --ingroup $NB_GROUP --disabled-password --gecos "" $NB_USER

USER polyaxon
```

**Comment by mouradmourafiq** [comment]
Next release all Polyaxon service will be running as non-root user, with fixed group id and user id: `RUN groupadd -g 2222 -r polyaxon && useradd -r -m -g polyaxon -u 2222 polyaxon`

**Comment by rapatel0** [comment]
THIS IS FUCKING AWESOME 

Can we specify the UID and GID in the chart deployment? We will probably have UID GID collisions without being able to control those.  Moreover, we can harmonize the access via the polyaxon group to files, mounts etc.

**Comment by mouradmourafiq** [comment]
[Security context](https://docs.polyaxon.com/configuration/security-context/) are in beta in the v0.5. Please feel free to create/reopen this issue if you have more ideas in mind to make this feature better.

**Comment by vnikiti** [comment]
This is still broken. Trying to install polyaxon helm chat, getting below issue.

```
  Normal   Pulled     11s (x4 over 44s)  kubelet            Successfully pulled image "polyaxon/polyaxon-api:1.6.2"
  Warning  Failed     11s (x4 over 44s)  kubelet            Error: container has runAsNonRoot and image will run as root
```

**Comment by mouradmourafiq** [comment]
You need to set the security context: https://polyaxon.com/docs/setup/platform/common-reference/#security-context

**Comment by vnikiti** [comment]
@mouradmourafiq  I tried that. I see `securityContext` spec on deployment resource that is specifying `fsGroup` but the pod spec ends up having the following. 

```
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
```

**Comment by vnikiti** [comment]
@mouradmourafiq I added `runAsUser` and `runAsGroup` to `securityContext` partial but now getting the following error in API pod.
```
Traceback (most recent call last):
  File "./manage.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/polyaxon/polyaxon/polyconf/settings.py", line 17, in <module>
    from polyconf.config_settings import *  # noqa
  File "/polyaxon/polyaxon/polyconf/config_settings/__init__.py", line 34, in <module>
    set_logging(
  File "/usr/local/lib/python3.8/site-packages/polycommon/settings/logging.py", line 28, in set_logging
    os.makedirs(log_dir)
  File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/polyaxon/logs'
```

**Comment by mouradmourafiq** [comment]
Can you share your config, we are running with this option without any issues.

**Comment by vnikiti** [comment]
@mouradmourafiq  Do you need a compiled Helm chart? Kubernetes cluster details? It seems that `/polyaxon/logs` is not owned by user specified by `runAsUser`. The issue is that the current version of the chart does not specify `runAsUser` and `runAsGroup` so all containers are running as root. You might not be seeing any issues because the Kubernetes cluster you are testing with does not enforce non-root user policy. While I really liked the product, I am thinking I will raise this issue with Polyaxon account team or simply look for other product. This product does not seem to treat security as an important concept and I work in a highly regulated space where security is a must. Why I say this product does not take security seriously is because by default everything runs as root which works fine in a sandbox environment but not enough for a production-grade environment that deals with valuable data.

**Comment by vnikiti** [comment]
Here's a little more details about the error.
<img width="1038" alt="Screen Shot 2021-03-09 at 6 59 14 PM" src="https://user-images.githubusercontent.com/1936580/110554933-b073cd00-8109-11eb-853c-9762bf3d9db2.png">

**Comment by mouradmourafiq** [comment]
We do not run the containers as root and we do not recommend that users to run the containers as root.

we optimize for defaults to allow users to try the community edition with the least amount of blockers, similar to the fact that we do not require HA for postgres, redis, artifacts store, registry, API ... we left Docker's default user. 
We have a best practices page for anyone trying to run a production environment.

If we require people to use all those steps, I'm sure we'll get more issues as people tend to skip reading the docs most of the time.
We use `gosu` to set the proper user and to adapt to volumes that users might mount at runtime, the error you are seeing is because you did not set the `securityContext` as suggested in the docs, or because you changed the chart, the script in the entry point did not correctly run to change the all required paths and set the scripts to the proper user. Since you did not answer the first question it's very hard to tell what you are trying.
 
This deployment practice, i.e. with `gosu`, is used by other open-source projects like sentry, sourcegraph, and so many others for their community deployments as well. If we set the uid and guid to a fixed value by default, we will have to tell people that they need to change their volumes to those values, gosu allows to let people mount their volumes without changes and to set the security context at the entry point.

If you have doubts about the security of the platform, I would suggest that you hire a freelancer to audit the code and the scripts for you, I am afraid we cannot provide custom deployments for the free edition.

Thank you.

**Comment by mouradmourafiq** [comment]
Starting from [v1.13](https://polyaxon.com/docs/releases/1-13/#deployment--setup) all pods will be running with `nobody:nogroup` and will assume no UID/GID.

All containers will have the following security context when enabled:

```yaml
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
```
All pods will have the following security context when enabled:

```yaml
    securityContext:
    runAsUser: {{ .Values.securityContext.user }}
    runAsGroup: {{ .Values.securityContext.group }}
    fsGroup: {{ .Values.securityContext.fs }}
```
