### ISSUE TITLE
[Feature Request] - Build Local Docker environment from configfile

### ISSUE THREAD

**Issue by rapatel0** [polyaxon/polyaxon#351]
As a machine learning engineer, I would like to run an experiment locally in my development environment for faster development and quick iterations.

Requirements
- Polyaxon-cli builds local docker container from config file
- Polyaxon-cli creates docker container from config file
- Polyaxon-cli mounts development directory to the container via bind mount.

Host Requirements
- Nvidia docker
- Nvidia driver
- Docker 18.03 or greater

Implementation 
- Templating with the same templating code in polyaxon/polyaxon

**Comment by mouradmourafiq** [comment]
Just an update, next release will introduce the possibility to use your own dockerfiles. So for users who want much control over how their images are created, they can opt for creating a Dockerfile, and use it instead of the generated one during the build.

Kaniko will be in beta in addition to the native builder.

**Comment by mouradmourafiq** [comment]
Running experiments locally will be supported in the next release v0.5, closing this issue for now.
