### ISSUE TITLE
Docs improvements on the parameters of Bayesian Optimization

### ISSUE THREAD

**Issue by vfdev-5** [polyaxon/polyaxon#360]
### Unclear documentation

Need improvements of the parameters of Bayesian Optimization:
```
  bo:
    n_iterations: 15
    n_initial_trials: 30
```
what are exactly: 
- n_iterations
- n_initial_trials

**Comment by mouradmourafiq** [comment]
n_iterations: is the number of times to run the bayesian process to create new suggestions based on the previous observations(experiments)
n_initial_trials: in order to run the algorithm, we create an initial set of random experiments, based on the performance of this initial sample (params -> metrics) the iterative process start suggesting the experiments for n_iterations times.

I somehow forgot about this aspect, I think optimization must really be a new first class section in the documentation, basically consolidating the stuff from concepts and reference.

**Comment by vfdev-5** [comment]
@mouradmourafiq thank you for explanation !

**Comment by mouradmourafiq** [comment]
The hp optimization has been moved to a separate reference section + some explanations, more info is coming.
<img width="509" alt="screenshot 2019-02-25 at 14 51 33" src="https://user-images.githubusercontent.com/1261626/53341921-541c2700-390d-11e9-92e9-9f1907934966.png">
<img width="989" alt="screenshot 2019-02-25 at 14 52 05" src="https://user-images.githubusercontent.com/1261626/53341922-161f0300-390d-11e9-96e7-2f9149d5a991.png">

Closing this as it will keep improving with time.
