### ISSUE TITLE
Add "Code" explorer on experiment pages

### ISSUE THREAD

**Issue by olivier-gillet** [polyaxon/polyaxon#417]
### Feature motivation

Now it is only possible to explore the config file launched for an experiment, but impossible to explore the whole code corresponding to the experiment. For example I can be useful to explore the code to check the way the experiment was implemented, or in the case of some parameters were not logged with polyaxon.

### Feature description

For example having a "Code" tab in addition to "Config" on experiment pages to explore the code corresponding to this experiment.

cc @vfdev-5

**Comment by mouradmourafiq** [comment]
This is planned for the v0.6, I will keep you posted about the progress.

**Comment by mouradmourafiq** [comment]
I think the logic in this area has changed a bit, since the way git is linked to experiments has been improved and standardized around git platforms [0][1], the links point directly to the git commit used in the experiment (which will take the user to github/gitlab/bitbucket ...). That being said if a run has code in the outputs the user can explore it in the outputs section [2][3].

![Screenshot 2020-03-31 at 13 11 02](https://user-images.githubusercontent.com/1261626/78020180-411a2880-7351-11ea-8357-3235a33ea620.png)

![Screenshot 2020-03-31 at 13 11 11](https://user-images.githubusercontent.com/1261626/78020197-48413680-7351-11ea-82ae-64cd6a320eb2.png)

![Screenshot 2020-03-31 at 13 11 40](https://user-images.githubusercontent.com/1261626/78020267-70309a00-7351-11ea-8767-78ad6396ea50.png)

![Screenshot 2020-03-31 at 13 11 54](https://user-images.githubusercontent.com/1261626/78020271-7292f400-7351-11ea-94dd-e324867d4a3d.png)
