### ISSUE TITLE
error in polyaxon postgresql

### ISSUE THREAD

**Issue by allenzhang010** [polyaxon/polyaxon#44]
do we need any seed data when install polyaxon ? I meet error in postgresql console:

ERROR:  relation "clusters_cluster" does not exist at character 164
STATEMENT:  SELECT "clusters_cluster"."id", "clusters_cluster"."created_at", "clusters_cluster"."updated_at", "clusters_cluster"."uuid", "clusters_cluster"."version_api" FROM "clusters_cluster" WHERE "clusters_cluster"."id" = 1

**Comment by mouradmourafiq** [comment]
Hi @allenzhang010, you are seeing those logs because, during the deployment, some pods are running (i.e. requesting the db) before the hooks, which means that the database is not initialized yet. As soon as the hooks finish, the db is synchronized. That being said the logs are still showing.

I would just ignore it, because that's not a real problem, as soon as the hooks are finished.

**Comment by allenzhang010** [comment]
how long the hook need to take or so? @mouradmourafiq

**Comment by mouradmourafiq** [comment]
It depends on the resources of your machine/cluster, if you have access to kubernetes dashbaord/kubectl you can watch the jobs as they run.

**Comment by solidpple** [comment]
i have same problem,

relation cluster_cluster does not exist
