### ISSUE TITLE
Experiment group reports as running even though all jobs have finished

### ISSUE THREAD

**Issue by jamescook106** [polyaxon/polyaxon#445]
Experiment group reports as running even though all jobs have finished

**Comment by mouradmourafiq** [comment]
This sounds like a bug, what type of experiment group are you running?

**Comment by jamescook106** [comment]
It was an experiment group which was running 100 random searches. It's defined kind in polyaxonfile.yml was group.

**Comment by mouradmourafiq** [comment]
I think I am going to close this as it's not relevant to the new system. We removed the concurrency from the core, it's now only handled by the agent/queue system, most of these issues were coming from race condition in the open source version because workers were accessing to the same global queue asynchronously.

Hopefully way less of these issues moving forward.
