### ISSUE TITLE
Support parallel downloading of directory

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#517]
We recently started using `polystores` to download the ImageNet dataset (1000 files, total 145GB) from GCS to local SSDs before starting training. `polyastores` is really easy to use thanks to automatically authenticating correctly to GCS.

Unfortunately `polystores` downloads the files single threaded / sequentially.

Downloading the data using `polystores` takes around 16 minutes. Doing the same download with `gsutil -m cp` takes only around 6 minutes.

Is there a way to support downloading multiple files with `polystore` in parallel?

@mouradmourafiq In the meantime do you know an easy way of authenticating `gsutil` inside a Polyaxon experiment to for faster downloading`

**Comment by lgeiger** [comment]
Thanks for the code snippet.

> Thinking about it we might just do that automatically in the init-container, so that the credentials are exposed by default whether the user uses python or any other tool.

I think this would be a great usability improvement. This way people have the option to use other commandline tools within the polyaxon file. E.g.:
```shell
gsutil -q -m -o Credentials:gs_service_key_file=$GOOGLE_APPLICATION_CREDENTIALS cp -r gs://my-bucket/data .
```

**Comment by mouradmourafiq** [comment]
All storage backends now implement a threading mechanism for downloading and upload directories, [see here](https://github.com/polyaxon/polyaxon/blob/master/core/polyaxon/connections/gcp/gcs.py#L318), it's still needs a bit more iterations, but this is similar to what gcp client does for parallel downloads.

This is used by the initializer mechanism for downloading artifacts/outputs from one step to another, or for downloading data from a store.

In case you have a specific usecase, you might just use one of the components based on the gsutil cli, boto cli, or azure cli, instead of Polyaxon's abstraction, the public components will be open sourced in the next few days.
