### ISSUE TITLE
Add 'scroll to bottom' button for logs

### ISSUE THREAD

**Issue by AdamHillier** [polyaxon/polyaxon#569]
Sometimes build/job/experiment logs are _very_ long and the only bit I need is the last few lines. Scrolling manually to the bottom is a pain if I have to do it frequently, e.g. every time I refresh the logs. It would be useful to have a button to just scroll to the bottom.

This is not a huge problem but would be nice to have.

**Comment by mouradmourafiq** [comment]
I agree, logs saving, loading, and UI were under-optimized for some time, but things change a bit since this issue was open as well as other issues.

I will address all issues related to logs in this thread:

 * Logs disappears if pod crashes: #679
 * Logs streaming maxes out at a few messages per second: #623
 * Add logs streaming to web ui: #81

As well as other issues that were mentioned in other threads, e.g.:
 
 * Accessing logs to debug a notebook or a tensorboard
 * Logs are slow to render
 * Logs are saved in a non-optimal way for long running jobs
 * logs require to click refresh
 * No logs when the init container is falling, users need to check the k8s the pod, and require to set a timeout which is not very practical.

It was mentioned in the blog post as well in several other issues, the new logging mechanism has some new features:

 * Logs storage is now sharded
 * Logs are not throttled, but to return faster request only a max of 2000 lines are fetched at the time, with a process to follow until the experiment is done or all logs related are fetched.
 * Logs are stored for jobs as well as services (notebooks, tensorboards, ...)
 * Logs from all containers are streamed and stored.
 
Serveral UI and CLI usability improvement for logs viewing:

 * CLI can now localize timestamps when streaming logs:

![Screenshot 2020-03-17 at 22 33 37](https://user-images.githubusercontent.com/1261626/76904851-11731700-68a1-11ea-89c4-af034662efce.png)

 * Users can also opt to remove the timestamp, or include information about the other containers and pods:

![Screenshot 2020-03-17 at 22 33 54](https://user-images.githubusercontent.com/1261626/76904904-26e84100-68a1-11ea-9d66-7e023414b60e.png)

 * Logs in UI show also localized dates with possibility to search 

![Screenshot 2020-03-17 at 22 27 36](https://user-images.githubusercontent.com/1261626/76905337-08367a00-68a2-11ea-8bb3-e1d94bf1515f.png)

 * Ui gives the possibility to set the number of logs lines per page.

![Screenshot 2020-03-17 at 22 28 52](https://user-images.githubusercontent.com/1261626/76905024-6c0c7300-68a1-11ea-8a92-3a95bfc86dc8.png)

 * Instead of having one way of orienting the logs, users can opt to sort by several fields, in this case you can use the timestamp `desc` to get the latest first, it's also possible to realtime-search the logs

![Screenshot 2020-03-17 at 22 49 42](https://user-images.githubusercontent.com/1261626/76905199-be4d9400-68a1-11ea-982a-6135666d7d54.png)

 * It's possible to resize the columns

![Screenshot 2020-03-17 at 22 28 05](https://user-images.githubusercontent.com/1261626/76905250-d9200880-68a1-11ea-855f-41bb3f4db13c.png)

 * Or hide some of them if they are not important

![Screenshot 2020-03-17 at 22 27 46](https://user-images.githubusercontent.com/1261626/76905315-f8b73100-68a1-11ea-9de1-e7d2ba668452.png)

I will close this issue for now, thank you for opening the issue.

**Comment by AdamHillier** [comment]
> It was mentioned in the blog post as well in several other issues, the new logging mechanism has some new features:

That's great to hear, thank you. Is there any more news about general availability of v1.0?
