### ISSUE TITLE
# of random search experiments limited by search space cardinality

### ISSUE THREAD

**Issue by aakhundov** [polyaxon/polyaxon#589]
### Missing Documentation

When one increases the `n_experiments` in [`polyaxonfile_hyperparams.yml`](https://github.com/polyaxon/polyaxon-quick-start/blob/master/polyaxonfile_hyperparams.yml) (from `polyaxon-quick-start` repo) to, e.g., `25`, the platform schedules `20` experiments instead. This happens because the following [lines](https://github.com/polyaxon/polyaxon/blob/0c47bd220bccf60d5af72af6dc9074f36903c029/polyaxon/hpsearch/search_managers/utils.py#L53) in `hpsearch.search_managers.utils.get_random_suggestions` are capping the number of suggested experiments by the cardinality of the discrete search space (which in the above-mentioned polyaxonfile is exactly `20`):

```python
    if all_discrete:
        space = reduce(mul, [v.length for v in matrix.values()])
        n_suggestions = n_suggestions if n_suggestions <= space else space
```

This behavior is not mentioned in the [Random Search](https://docs.polyaxon.com/references/polyaxon-optimization-engine/random-search/) documentation page. What makes things even more confusing is that, when an experiment group is scheduled from the CLI, it outputs the following:

<pre>
Creating an experiment group with the following definition:
---------------------  ------------------
Search algorithm       random
Concurrency            5 concurrent runs
Early stopping         deactivated
<b>Experiments to create  25</b>
---------------------  ------------------
Experiment group 47 was created
</pre>

In my opinion, the capping behavior should be removed, as the value of `n_experiments` should dictate the number of experiments scheduled. Also, a user may actually want to run more experiments in a group than there are configurations in the search space (e.g., for estimating the uncertainty of each exact configuration).

If it is going to stay, the documentation and the CLI output should be modified to avoid the confusion. It may also make sense to extend the search space in the `polyaxonfile_hyperparams.yml`.

**Comment by mouradmourafiq** [comment]
If you want to have an uncapped behaviour for the experiment group, you should at least include one param with a distribution instead of a discrete space, this way the algorithm can generate more suggestions, otherwise the space will have non-unique suggestions.

Regarding the documentation, I agree it should be mentioned somewhere that the algorithm will do best effort to generate the requested number of experiments, the unique behaviour is essential to at least generate random suggestions, and avoid duplicates.

In future Polyaxon versions, the hyper-tuning will include the current algorithms, but will also expose an interface so that users can alter the behaviour/code or create their own algorithms.

Sorry for the confusion.

**Comment by aakhundov** [comment]
Thank you for the explanation. Looking forward to having extensible hp-tuning algorithms.

Just to make this clear: is the requirement that every suggestion is unique (in terms of the picked hyper-parameter values) critical for the downstream process / management of the experiment group? I.e., will something downstream break if two or more experiments in the same group have identical set of hyper-parameter values?

**Comment by mouradmourafiq** [comment]
It will not break the algorithm in terms of scheduling, but if the current logic does not check for duplicates, it might create X random experiments where 60% are basically identical (I picked a large number intentionally), I can see that in some instance it could be desirable behaviour maybe with a capped percentage of duplicates. 
I think the best design would be to give more power to the end user to create custom logic, instead of adding more params to the current algorithms, that's why we are pushing to get this behaviour for the next release. Users can create a job to generate the space based on some logic, or just provide the suggestions' space to be use to create experiments.
