### ISSUE TITLE
Show names of experiments in tensorboard

### ISSUE THREAD

**Issue by MatthiasKohl** [polyaxon/polyaxon#608]
### Feature motivation

When starting a tensorboard for the whole project or a group, it would be very useful to be able to filter based on the names/description/tags of the experiments, using regex, just like tensorboard offers. Currently (Polyaxon 0.5.6), it seems like tensorboards for projects are just started with the whole outputs folder of the project and tensorboards for groups are given names and folders to the experiments in the group, with the names not being particularly descriptive (essentially only the ID is of any use there).

### Feature description

Descriptive names in group/project tensorboards, allowing filtering based on regex.

### Feature implementation

When starting the tensorboard process, just submit the actual name of the experiments and a reference to the experiment's output folder (as done for group tensorboards now but using the actual name).
Even better would be to create a special folder structure somewhere, then insert symbolic links to a certain selection of filenames in the output folders (such as events.*) and name those folders accordingly, then start tensorboard at the top-level. The reason for creating a special folder structure for tensorboard is because tensorboard used to take a lot of resources when running on folders with large outputs (this may be fixed now, but I'm unsure). In any case, it allows to just consistently set the names of experiments as expected in tensorboard, which is very helpful.

**Comment by mouradmourafiq** [comment]
Hi, this just an update on this issue, in v1 there are at least 3 pre-packed components for Tensorboard:
 * based on experiment uuid
 * base on a path (which means you can sync runs coming from outside polyaxon): s3/gcp/azure/nfs ... 
 * based on performance / search query; e.g. `query=metric.loss<0.01, sort=metric.loss, limit=15`  will only prepare a tensorboard with the top 15 experiments based on their loss metric, the sort is to used to ensure a ranking.

**Comment by lgeiger** [comment]
@mouradmourafiq I think this issues isn't fully resolved with v1 yet. The names of different jobs still aren't rendered in the TensorBoard, or am I missing something?

In v0.x this was managable since the experiment ID was a simple counter which was possible to remember. With the change to UUIDs it is very hard to compare different runs in a TensorBoard since remembering full hashes is quite cumbersome. E.g. checkout the naming of the runs in this example from the docs:
![](https://polyaxon.com/static/9e59ba95de0aabbbc5cef7e79662c61a/8c76b/tensorboard.png)

**Comment by mouradmourafiq** [comment]
The problem with names is that they are not unique values, and it very hard to link back to a run with the name.

**Comment by mouradmourafiq** [comment]
What could be done is to provide a simple collapsible sidebar with runs information, similar to the comparison table/visualization, what do you think?

**Comment by lgeiger** [comment]
> The problem with names is that they are not unique values, and it very hard to link back to a run with the name.

I see, in v0.x names within a project used to be unique (otherwise Polyaxon would append a number to it).

Is it necessary to have unique names for TensorBoard to work properly? Otherwise I would argue that while names are not necessary unique they carry meaning to the user comparing runs whereas hashes are unique but usually don't help when comparing runs with more than 2 or 3 experiments. Especially when coming back to an already running TensorBoard after lunch usually all meaning is lost even with IDs but hashes tend to make remembering even more cumbersome.

**Comment by mouradmourafiq** [comment]
One quick way to have this right now is to customize the [tensorboad path](https://polyaxon.com/docs/experimentation/tracking/client/#get_tensorboard_path) during the execution

The default subpath is `tensorboad`, users might use more meaningful paths using params, tags, name or all for example:

```python
inputs_suffix = '-'.join(['{}={}'.format(k, v) for k,v  in tracking.run_data.inputs.items()])
trakcing.get_tensorboard_path(rel_path='tb-{}'.format(inputs_suffix))
```
Both the tracking module and Run instance have full information about the run before it gets executed based on the data in the polyaxonfile or params passed from CLI/Operation.
 
The tensoborad will be saved under a custom subpath. That being said it does not mean that the init process should not be optimized to give more flexibility, but this could be a viable workaround and used now.
