### ISSUE TITLE
Scheduling many jobs at the same time leads to zombie state jobs (possible race condition?)

### ISSUE THREAD

**Issue by MatthiasKohl** [polyaxon/polyaxon#610]
### Describe the bug

It's hard to consistently reproduce, but when scheduling many jobs such that the build happens to be at the same time, it seems like we can get the following scenario:
K8s correctly schedules the pods according to their requests/limits and the available resources. Polyaxon however believes that some jobs are running although they are unschedulable by K8s. When freeing up resources quickly enough, K8s actually schedules those jobs and nothing else happens. However, if resources are blocked long enough, Polyaxon's heartbeat service will automatically stop these jobs (that it believes are running although they are unschedulable by K8s) and fail them.
To me, this could be a critical bug in the scheduler and really seems like some kind of race condition. I haven't tested it with multiple users, but I assume this would occur if many users submit different jobs at the same time (a likely scenario).

### To Reproduce

1. Create a job with a fairly large build and long runnning time (>2000 seconds).
2. Make sure that only two of these jobs can run on the cluster at a time (by requesting resources accordingly).
3. Run this job many times with polyaxon run -f polyaxonfile.yml  (submit this command again as soon as it terminates and repeat 5 times)

### Expected behavior
The jobs should just be recognized as unschedulable and scheduled when the resources become available again.

### Environment
Polyaxon 0.5.6, Kubernetes 1.15.4

**Comment by mouradmourafiq** [comment]
There's a section about heartbeat and zombie state in the docs, please search for that section for more information.

**Comment by MatthiasKohl** [comment]
> There's a section about heartbeat and zombie state in the docs, please search for that section in the docs for more information.

Would it be possible to provide a link? If I go to docs.polyaxon.com and look for heartbeat or zombie, nothing shows up.

The only thing I found is something in the release notes which explains that the heartbeat logic exists. However, my problem is NOT that the heartbeat logic exists, rather that polyaxon recognizes unschedulable jobs as running under certain circumstances which are unclear to me.

**Comment by mouradmourafiq** [comment]
Sorry about that, you are right, the docs does not have info about that behaviour because it will be removed, you can set `TTL:HEARTBEAT` in the settings page > more options to a large number: e.g. `10800`  (3h == 60*60*3)

But you have to restart the services (api, scheduler, and cron) or run upgrade of the platform because that value is cached.

**Comment by MatthiasKohl** [comment]
But could you explain precisely what behavior will be removed ?

**Comment by mouradmourafiq** [comment]
If a job is passed to k8s and is not schedule for a certain time (TTL:HEARTBEAT), the platform will collect it as a  zombie state, and will just stop it. The behaviour has changed, is the correct wording, to be reconciled directly in kubernetes, see the [termination section](https://github.com/polyaxon/polyaxon/blob/master/cli/polyaxon/schemas/polyflow/termination/__init__.py#L26), that's why the config option is not appearing on the docs.

**Comment by MatthiasKohl** [comment]
If I'm not mistaken, the version I'm using (0.5.6) is the latest version.
Could you explain exactly what behavior changed ?
Since I'm seeing this, it clearly hasn't changed in that particular case at least.

My problem here is NOT that there are zombie state jobs or that they are collected by the heartbeat service, my problem is that they are incorrectly recognized as zombie state (since they are simply unschedulable).

**Comment by mouradmourafiq** [comment]
> Could you explain exactly what behavior changed ?

Changed in the upcoming version, not in the v0.5.6, sorry I was not clear about that.

> since they are simply unschedulable

If they are unschedulable for a long time then at some point they will be recognized as zombie, that's why there's a heartbeat ttl period, otherwise a job might stay in unschedulable forever.

**Comment by MatthiasKohl** [comment]
> If they are unschedulable for a long time then at some point they will be recognized as zombie, that's why there's a heartbeat ttl period, otherwise a job might stay in unschedulable forever.

This would make sense if all jobs would be recognized as zombie, but most jobs are actually in a "warning" state and then run just as expected once they become schedulable. So why are just some jobs recognized as zombie?

Concerning jobs that might stay in unschedulable forever: how will this be prevented in future versions? If the user submits a job that can never be scheduled then it should be up to him to clean it up (and up to polyaxon to provide means to clean it up but that seems to be the case), right?

**Comment by mouradmourafiq** [comment]
> Concerning jobs that might stay in unschedulable forever: how will this be prevented in future versions? If the user submits a job that can never be scheduled then it should be up to him to clean it up (and up to polyaxon to provide means to clean it up but that seems to be the case), right?

That's exactly what the zombie state is for, there's a TTL and then it get's cleaned.

I am sorry, I feel that we are talking about the same thing but in different languages, if you want all jobs to stay in warning and then get scheduled, please follow the instructions in one of the comments earlier.

**Comment by MatthiasKohl** [comment]
OK, I will close this issue as most jobs worked as expected for me. This is still a clear bug, but it would take me too long to provide screenshots/logs to show you where the exact issue is, and it might be fixed with a future version anyway. I'll re-open in case this will be relevant in the future.

**Comment by mouradmourafiq** [comment]
Thanks for the feedback, it's definitely a confusing behaviour for other users as well, and not well documented, that's why the behaviour have changed.

**Comment by yigitsoy** [comment]
This happens to me as well, when I submit many experiments (each requiring one GPU) while I have only a few GPUs available. Environment is the same.

I saw the following cases

1. Experiment gets created and scheduled immediately and waits in "warning" state until a GPU becomes free. Then it starts running.

![image](https://user-images.githubusercontent.com/5089181/71358169-5d573e00-2588-11ea-9694-2dfaa1f1092d.png)

2. Experiment gets created and waits in "created" state until a GPU becomes free. Then it gets scheduled and starts running immediately.

![image](https://user-images.githubusercontent.com/5089181/71358402-1453b980-2589-11ea-840a-fbc8bd034937.png)

3. Experiment gets created and waits in "created" state. At some point it gets scheduled and waits in "warning" state again until a GPU becomes free. Then it starts running.

![image](https://user-images.githubusercontent.com/5089181/71358510-73b1c980-2589-11ea-85c0-c9da70d4c7d0.png)

4. Experiment gets created and waits in "created" state. At some point it gets scheduled and starts running. After a while it fails/gets killed due to being in zombie state.

![image](https://user-images.githubusercontent.com/5089181/71358638-e8850380-2589-11ea-8b87-d62079aefb02.png)

Apart from the issue of zombie state, the fact that some of the experiments wait in "warning" state while others wait in "created" state confuses.

**Comment by yigitsoy** [comment]
I am still having this issue. If I submit multiple experiments (#experiment > #GPUs) or more than one group of experiments each having more experiments than the number of GPUs, the experiments that are supposed to be nonschedulable and should wait, get scheduled and start running. But since there are no resources, they get stuck in zombie state. 

I have only two GPUs on a single node and the relevant section of my polyaxonfile looks like the following;

```yml
version: 1

kind: group

build:
  dockerfile: Dockerfile
environment:
  resources:
    cpu:
      requests: 5
      limits: 8
    memory:
      requests: 20480
      limits: 32768
    gpu:
      requests: 1
      limits: 1
hptuning:
  concurrency: 2
````
This group has more than two experiments and I see the issue when I start two groups of experiments with this configuration.

Is it possible to re-open this issue and investigate a bit further or should I create another issue?

**Comment by mouradmourafiq** [comment]
@yigitsoy in the settings page, under more options, just set `TTL:HEARTBEAT` to a large number, e.g. 3  hours (`10800`).
The behaviour that you see is what's described in this thread, if a job is not scheduled for a long time (> the ttl heatbeat) then the scheduler will collect it as zombie.

**Comment by yigitsoy** [comment]
Like Matthias, I also understood that you we could set ttl:heartbeat to a
large value. But what if after 3 hours the resources are not yet free? I
have jobs running from 10-30 hours. I do not think ttl is the problem
here.

The fact that the experiments are scheduled and got the state 'running',
even though the required resources are not available yet, is the issue. I
am not familiar with the architecture but it seems the scheduler should not
start a job before resources are not available again.

Interestingly, as I shared screenshots in an earlier post, this works as
unexpected now and then and an experiment stays in 'created' state until a
you becomes available again, even if it takes 30 hrs.

**Comment by mouradmourafiq** [comment]
I completely understand that this issue is confusing, in v1 it was already fixed, and what you are describing is exactly how it works, the last state the scheduler sets is `scheduled`, everything after is managed by the operator. As soon as the open source version is released this should be considered fixed.

**Comment by yigitsoy** [comment]
Thanks a lot for the explanation. I am looking forward to the release of the open source version for v1.

**Comment by nlarusstone** [comment]
I'm still using 0.5.6 and would like to set the TTL Heartbeat value to a larger value while waiting for the release of v1. Would someone be able to point me to where I can find this setting? Thanks!

**Comment by mouradmourafiq** [comment]
@nlarusstone  You can set the `TTL:HEARTBEAT` in the settings page, under `more options`, one field is the key (`TTL:HEARTBEAT`) and the value is in seconds, iirc the default value is 30min == 1800

**Comment by nlarusstone** [comment]
Excellent, thanks so much for your quick response! Looking forward to open source v1
