### ISSUE TITLE
How to pass AWS ECR credentials?

### ISSUE THREAD

**Issue by stratospark** [polyaxon/polyaxon#688]
Using polyaxon 0.5.6

Trying to follow the directions here: https://docs.polyaxon.com/integrations/ecr/

```
{
    "credsStore": "ecr-login"
}
```

Wondering if instructions have been verified? Where would we put in our aws_access_key_id and aws_secret_access_key?

**Comment by mouradmourafiq** [comment]
ECR is quite difficult to setup in Polyaxon v0 because of the rotating mechanism, one way to use ECR is have a secret attached to the experiments where you provide the login. I know that some teams managed to use ECR by using a cron to reauthenticate to ECR and update the k8s secret used by the experiments.
v1.0.5 core just got merged, the open source persistence layer will be merged soon as well, and it's more flexible and it will allow users to use ECR more easily compared to v0.
