### ISSUE TITLE
bayesian optimization - after the initial trials concurrency is 1

### ISSUE THREAD

**Issue by OodapowUiPath** [polyaxon/polyaxon#707]
### Describe the bug

The iterations after the first schedule the new experiments one by one.

### To Reproduce

A link to the code used to launch the test is [HERE](https://github.com/Oodapow/polyaxon_example/blob/master/polyaxon/hptune_bo.yml)

### Expected behavior

At each iteration a number of experiments equal with the concurrency to be scheduled.

### Environment

Environment:
 * kubectl
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:31:31Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```
 * helm
```
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
```
 *  polyaxon version
```
Current cli version: 0.6.1.

Supported cli versions:

--------------  -----
latest_version  0.6.1
min_version     0.5.0
--------------  -----
```

**Comment by mouradmourafiq** [comment]
This is expected behavior for Bayesian optimization, the concurrency only applies to the random/seed step (the first observations), after that the optimization is applied sequentially on the whole space including new observations created in each iteration.

Polyaxon v1 allows to use previous experiments in a projects as a seed without doing the random search step.

closing this issue as wontfix.
