### ISSUE TITLE
version 1.1 polyaxonfile

### ISSUE THREAD

**Issue by OodapowUiPath** [polyaxon/polyaxon#821]
the 0.6.1 CLI is not supporting polyaxonfiles of version 1.1

**Comment by mouradmourafiq** [comment]
To install the new cli you need to use `pip install polyaxon`, unfortunately it's not backward compatible with v0. A private discussion about some of the changes and motiviation:

> me: it’s planned to have a manual migration guide, but in general, the new spec is almost similar to the previous one in terms of sections, but one big change is that the new spec is camel case.
I think this change needs to be explained, because before, the spec was snake case, but since users were adding k8s specifics, e.g. tolerations, … they had to write them in camel case, we just consolidated the spec around camel case.
To make also the platform extendable with plugins and generic components (like tensorboard and notebook they used to be baked into the platform), we had to make the dsl support more k8s stuff, e.g. dns changing on the container or pod level, and to reduce validation and type checks, the platform inherits directly from k8s protos, for container spec and tolerations, affinities, node selector, …, all of them are camel case, so it was necessary to make the complete dsl camel case.
I think this is the single major migration users will have to do if they want to keep using  the open source since >2years
the new spec is, I believe, very simple, very extendable and have a good architecture for furture work

> user: someone from community could provide a simple script to convert previous yaml to the new compatible one if possible...

> me: That would be amazing, but I think it’s a large amount of work, maybe supporting a small subset of fields could be enough initially. I tried to do that for the paying customers but we ended up migrating manually, because of specific fields.
