### ISSUE TITLE
Show logs after experiment is finished

### ISSUE THREAD

**Issue by gzcf** [polyaxon/polyaxon#86]
Current behavior of `polyaxon experiment logs` don't show logs after experiment is finished, it just show `Session ended` merely.

```
$ polyaxon experiment -xp 2 logs
Session ended
```

Is it a expected behavior? Or something went wrong for me?

**Comment by mouradmourafiq** [comment]
Currently `polyaxon experiment -xp 2 logs` will only stream logs while the experiment is running. You can get the logs manually by using ssh in the logs volume.

It's planned to add the functionality to use the same command to stream logs of already finished experiments in one of the next releases, as well as getting the logs from the dashboard.

**Comment by gzcf** [comment]
Sounds great :)

**Comment by gzcf** [comment]
@mouradmourafiq I am going to do this.

These is my brief design:

* Create a model `ExperimentLog(uuid, experiment_id, job_id, content)`, persist logs in celery task `handle_events_job_logs`
* Add logs ui in experiment and job pages which display saved logs
* modify `polyaxon experiment logs` to print saved logs. And use `-f` option to stream logs.

Currently, I don't want to combine saved logs and streamed logs to  a single view. Because there would be a problem of duplicate logs or lost logs. For example, If access saved logs then access streamed logs, some logs between two accesses will be lost so that we can provide a consistent 
view of logs.

Do you have any suggestion?

**Comment by mouradmourafiq** [comment]
@gzcf Do we need a model for this? I mean the logs are already persisted in files. We can just assume that when a user requested a running experiment that we should serve the streamed logs, otherwise we should go directly to the location of the logs and stream from reading a file.

Each experiment has logs and we can access them `get_experiment_logs_path`. We can add another level for jobs and a paths utils with  `get_job_logs_path`.

Currently we persist logs on experiment level by combining all logs from other jobs. In order to persist logs on job level also, we need to modify as you mentioned `handle_events_job_logs`, so that not only we save th combined logs for the experiment but also a logs per job.

**Comment by mouradmourafiq** [comment]
My question regrading a new model is important because, we already request from users to provide a volume for logs and outputs, which means that the user will have one place to persist and access logs, either through Polyaxon or through command lines. also in the future Polyaxon will have also views to download outputs/artifcats, and I don't think we will create models for that. 

The projects/groups/expeirments models already provide and automate the creation of the folders/files for creating the logs, so we just need to provide views to access them.

The CLI will basically decide which view to access, based on the last status of the experiment. We should have some extra handling on the views themselves to check that they can serve logs based on the status of the experiment.

**Comment by gzcf** [comment]
Emm. I am not aware of the fact that after user provides a volume using `PersistentVolumeClaim`, all pods see the same volume and web service can access logs no matter what experiment writes.

So I will just provide views to access logs.

By the way, currently we don't need job level logs.

**Comment by mouradmourafiq** [comment]
Yes depending on the `PersistentVolumeClaim` some of them have can be mounted to all nodes, and all data, logs, and outputs volumes are mounted to the experiment pods, so that they can access these paths, these very same paths are also accessible to API and some of the worker depending  on if they need to have access or not.

This a choice to make sure that user data is persisted, without the need to keep the pods alive after they finished their job.

To have a better idea, you can start an experiment, and you can check logs and outputs structure on your node, you can also do that programmatically with python to see that everything stays unless the user decides to delete the project or the experiment.

Yes, we can just provide a view for now for the experiment, and make the job level logs as follow up issue. That was also my thinking when I created the issue.
