### ISSUE TITLE
[question] difference to other platforms

### ISSUE THREAD

**Issue by geoHeil** [polyaxon/polyaxon#88]
Hi,

what is the difference between you and:
- http://clipper.ai
- https://www.acumos.org
- https://predictionio.apache.org

you all seem to run on k8s and in one way or another provide some easy way to deploy models, also might offer some turn key models.

**Comment by mouradmourafiq** [comment]
Hi @geoHeil, I agree with you, there are many platforms and solutions for data science teams.

From the list you mentioned none of those platform are solving what Polyaxon is attempting to solve.

Looking at those solutions, what I can say is that:
 * http://clipper.ai is a platform that tries to solve the deployment process by providing a prediction serving system for machine learning. 
 * https://www.acumos.org seems to be a full fledged **hosterd** solution that tries to solve the whole lifecycle of ML and a marketplace. It also seems that for the moment only the marketplace is functional.
 * https://predictionio.apache.org is a ML stack for spark, in fact the solution is bundled with Apache Spark, MLlib, HBase, Spray and Elasticsearch.

Obviously, it's very hard to choose a solution, as @elgalu mentioned, there are other players trying to solve some specific issues related to the life cycle of developing ML models and deploying them.

Polyaxon is quite different than the other solutions in the following ways:

 * The main objective of the project is to reduce technical debt in the ML lifecycle, by automating and abstracting many steps that ensure that all experiments are reproducible.
 * The second important objective of the project is knowledge distribution within the teams, the platform provides user and organization management tools to increase knowledge distribution and role management. 
 * Currently the platform only focuses on the building and training phases and tries to introduce rigour and best practices during the training phase.
 * As was mentioned, automation is one of the most important features of this platform, in fact training and scheduling experiments requires many different technologies, for instance the pipeline.ai project bundles different other porjects, like airflow, openfaas, ... This not only makes a steep learning curve, namely for data scientists who should focus only on their algorithms and not how to glue different platforms, but also introduces many dependencies and system management issues. Polyaxon tries on the hand to provide a very simple and unique interface to solve some issues and not all of them, that being said the platform can easily work side by side with other tools, one can for instance train and track the activity logs of a model on Polyaxon, and decide to deploy it using openfaas, kubeless, seldon, or any other platform.
 * Some of the solution mentioned in your list also introduce hard dependencies, and can easily lock your teams and organization with that solution. Polyaxon only provides strucutre to your projects, the only dependency that you will introduce is declarative yaml files that define how to execute and train your models, so there's no lock in.

I know that this is not a very extensive answer to your question, because ML not only inherits all problems that software can have but also adds to it other dimensions of technical debts. 

I hope that my answer gave you an idea about the project and its mission.

**Comment by geoHeil** [comment]
@mouradmourafiq what about https://www.seldon.io or https://github.com/kubeflow/kubeflow they seem to something pretty similar.

**Comment by maver1ck** [comment]
I started with kubeflow and from my perspective deployment system they choose (ksonnet) is unacceptable. But they have one feature which polyaxon lacks - model serving.
Is there any plan to add tf_serving to polyaxon ?

**Comment by mouradmourafiq** [comment]
I just created the first draft of [action](https://github.com/polyaxon/polyaxon/tree/master/polyaxon/action_manager), there will be a lot of different actions: database connections, webhooks, triggers, deployment actions, registry actions, artifact actions... That the user can use before/after an experiment. But it will take a bit of time to have all that in place :)

**Comment by mouradmourafiq** [comment]
Well, what I meant by "deployment actions" is basically an integration with the different deployment providers: sagemaker, azureml, seldon, ..., basically an action/integration for each provider, the user will decide what to integrate and how the integration should be triggered.

Regarding the  "bus factor", I can understand that, and I know that more information should be shared regarding the project's objectives, roadmap, better documentation both for deployment and development, and viability of the overall project.
