### ISSUE TITLE
Bring back support for uploading code and interactive experimentation

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#887]
### Use case

In Polyaxon v0.x it was possible to run experiments interactively by using either `polyaxon upload` or `polyaxon run -u` to execute experiments with the latest local changes. This was particular useful when experimenting with neural networks which allowed for an interactive way of quickly testing and exploring changes without the need to commit and push.

It looks like [`polyaxon upload`](https://polyaxon.com/docs/core/cli/upload/) and `polyaxon run -u` have been disabled due to the removal of the internal `git` registry.

Are there any plans to bring back the internal `git` registry (either in CE or the commercial offering) or is there an alternative workflow to support this?

### Feature description

I guess this could be handled by reintroducing an optional internal registry or by utilizing the external git provider and adding the option to allow `polyaxon run -u` to either force push to a default `polyaxon-runs` branch or by pushing a new branch per interactively started Polyaxon Run.
I think the latter option would be a very useful feature to bring back some of the interactive experimentation workflow of v0.x with the added bonus of having a unique `git` hash for each run that is tracked by the external git provider.

**Comment by mouradmourafiq** [comment]
There are a couple of plans for the upload command:
 *  Upload to the default artifacts store or another artifacts store in the connections similar to v0 but very complex deployment and errors, very unlikely. Also several users have been asking about exposing the git so that they can run git commands.
 * As you mentioned, configure a github project that the upload command will just trigger a commit and push force to a dev branch. The benefit is that you can use the git repo as you would do normally, you have full commits, and can view changes in a system that is designed for that (github, bitbucket, gitlab). 

Currently what you mentioned is the best way to achieve fast iterations and is possible. User should use a `dev` branch (otherwise master is the default branch), for every change the user wants to trigger a job `git commit -a -m 'update' && git push origin dev` then just run `polyaxon run -f ...` as you would do.

The polyaxonfile should link to a public repo similar to the quick start example or a private repo, for example using a connection in the catalog:

```yaml
  init:
  - connection: repo1
    git: {branch: dev}
```

Polyaxon will by default inject latest code from that branch, add a lineage entry with the git commit, and start the container. The docker image should only be updated if a new dependency needs to be installed.

The run will have information about the git commit with a clickable link to the diff:

<img width="1339" alt="Screenshot 2020-07-06 at 16 09 24" src="https://user-images.githubusercontent.com/1261626/86602711-58e1f800-bfa3-11ea-949f-0d8ee75ee8a9.png">

Note: The lineage is not enabled for the CE version yet, but should be in the coming days. Also may be this workflow can be added to the docs as a recipe, since this is not the first time such question was asked from v0 users.

**Comment by mouradmourafiq** [comment]
Adding more context on what the feature should include:

 * `polyaxon init` should:
   * warn the user if the current project location does not have git project, and that the current branch will be used for interactive workflow.
   * It should also ask the user if they want to automatically inject a connection for providing necessary auth to pull the git repo. By default if the user has the init section in a polyaxonfile the CLI should not do anything, otherwise it should inject the init section with current branch, possibly set the commit, and the connection that was configured.
 * `polyaxon upload` or `polyaxon run -u` should:
   * trigger `git commit -a -m "update"` we can allow a `--message=` for adding a custom commit message.
   * trigger `git push`
   * Check if the polyaxonfile has an init section with configured connection otherwise inject it.
   * Submit run.

This workflow could be much useful than uploading code, and can be easily used with other external systems to submit jobs.

**Comment by lgeiger** [comment]
The proposed workflow sounds great, especially if Polyaxon would automatically inject the correct connection for the necessary auth. Another option would be to push a new branch per experiment, but not sure if this will get very messy when running large amounts of experiments.

> trigger `git commit -a -m "update"`

I think it would be great to also autopopulate the commit message with somthing like `polyaxon#<run id>` or `polyaxon@<run id>` so that users could use [GitHub's autolink feature](https://docs.github.com/en/github/administering-a-repository/configuring-autolinks-to-reference-external-resources) to automatically link back to the relevant Polyaxon experiment. This is a minor detail but could greatly impove user experience.

**Comment by mouradmourafiq** [comment]
> autopopulate the commit message with somthing like polyaxon#<run id> or polyaxon@<run id>

This is possible, but it could fail, one of the reasons to move from id to uuid was to allow generating unique ids outside of the DB, so we can allow that as flag, but there's always a risk of collision. The `git commit/push` needs to happen before submitting the run, so in order to do that the `uuid` will be generated first and it will be used in the commit message and as a run id.

Another option is the upcoming `github` hooks/notifications, where users can use send info to github, similar to slack/pageduty/...

**Comment by lgeiger** [comment]
> Another option is the upcoming github hooks/notifications, where users can use send info to github, similar to slack/pageduty/...

That's an interesting idea, I guess polyaxon could comment on the relevant commit or use the [deployments API](https://docs.github.com/en/rest/reference/repos#deployments) similar to how [integrations like vercel](https://vercel.com/github) handle it.

**Comment by mouradmourafiq** [comment]
A couple of more notes talking with more users about this issue since it is scheduled for v1.1.8:

Q: > Making a commit for every small change seems too much, is it possible to delay the commit until at least the experiment runs successfully.
A: I think we need to make sure that while iterating the user should be on a dev branch, commits are cheap, and the branch can be deleted completely if not useful at the end of the day. Users can always merge back to a prod/main/master branch.

Q: > Should we include Polyaxonfiles in the git repo? When changing just the polyaxonfile, e.g. a typo, does it make sense to still make a commit?
A: I think this is something that was confusing in Polyaxon v0 as well, a lot of users were asking for avoiding builds when only the Polyaxonfile changes. Polyaxonfiles are of course tracked on Polyaxon for every experiment scheduled, for git it makes sense to track the Polyaxonfile when the purpose is sharing / or persisting the experiment configuration, e.g. the quick-start repo. When developing and iterating on a new experiment, running `polyaxon run` with `-u` should be optional for intermediate small changes, the changes should be committed to the master branch to have a clear state of code and execution spec. 

In the end the `upload` command should be a utility function to streamline the process rather than set a rigid workflow. Polyaxon should just follow similar dev patterns used everyday, committing to github when developing a feature, and then merging to master when the feature is finished and stable.

**Comment by mouradmourafiq** [comment]
Discussion on Slack: https://polyaxon.slack.com/archives/C6QBND2SV/p1603304633113100
