### ISSUE TITLE
Info column in jobs table cannot be resized -> (reduce the intial width of UUID field)

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#893]
### Describe the bug

The info column in jobs table cannot be resized whereas all other columns can.

### To Reproduce
![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/13285808/86652649-df6af980-bfe4-11ea-8bdc-fa9680fa7e53.gif)

### Expected behavior
Info column can be resized

### Environment
v1.1.1 CE

**Comment by mouradmourafiq** [comment]
Not a bug, the width is fixed for some 2 first columns.

**Comment by lgeiger** [comment]
> Not a bug, the width is fixed for some 2 first columns.

Is there a reason for this? For me it seems like the experiment name is one of the more important informations on this table and it would be great if users could enlarge it.
As an alternative, to make this table less cluttered maybe shortening the UUID to 7 characters in the UI similar to how GitHub handles commit hashes would make a resizable column less important.

**Comment by mouradmourafiq** [comment]
The name has max length of `128` and I believe the length of the info field is also `120` or `128` not sure but it should match the max length of the name. So we just assume that a run info should be displayed, if there's a name we show it otherwise the uuid is displayed, and that's also the reason why the uuid column is visible by default because there might be names. 

Maybe we can reduce the initial width for the uuid field, and the user can decide to enlarge or use the expand feature when clicking on the cell.

**Comment by mouradmourafiq** [comment]
Actually this a bug, the length of the info field is `120` but it's not `120 characters`, so I guess we should allow resizing of the info column as well.

<img width="579" alt="Screenshot 2020-07-07 at 00 34 04" src="https://user-images.githubusercontent.com/1261626/86658753-95d0dd80-bfe9-11ea-8ebf-b9eecb622134.png">

**Comment by mouradmourafiq** [comment]
I just now recall why the column has been fixed as a leading column:
 * Flyout mode depends on it and it must be visible in the dashboard view.
 * It should not be used in the columns ordering logic (must be first all the time).
 * Since the value is artificial, it does not make sense for sorting as well.

We changed the logic to allow users to use names as any other field without defaulting the value to uuid, which means they can order/hide/show/filter by names as well, and the value has resizing and expansion mode.
For flyout mode there's a new icon `->/<-`.
<img width="622" alt="Screenshot 2020-07-08 at 17 45 34" src="https://user-images.githubusercontent.com/1261626/86940248-dbed8480-c142-11ea-87d5-fcc874590659.png">

A new release v1.1.2 is coming today with several enhancement and fixes.
