### ISSUE TITLE
Sidecar sync should support deletion

### ISSUE THREAD

**Issue by mouradmourafiq** [polyaxon/polyaxon#981]
### Current behavior

Polyaxon sidecar artifacts sync does not remove artifacts if they no longer exist in the context.

### Enhancement

The sidecar should support full context sync.

**Comment by lgeiger** [comment]
I am currently running into this issue when using [`tf.keras.callbacks.experimental.BackupAndRestore`](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/experimental/BackupAndRestore) which continuously stores checkpoints of the format `backup/chief/ckpt-{epoch}.index` every epoch to allow for automatic resuming after machine failure. This callback will automatically cleanup old checkpoints after each epoch and fully remove the directory after training has been completed. This cleanup is quite important since the checkpoints can easily take up many GB of storage.

Previously we wrote the checkpoints and all output directly to GCS instead of relying on Polyaxon to handle syncing.
What is the recommended usage with Polyaxon v1? Is it better to rely on Polyaxon to sync the output directories or should user code directly write to GCS?
Writing directly to GCS is easy to do with TensorFlow since GCS is automatically supported via [`tf.io.gfile`](https://www.tensorflow.org/api_docs/python/tf/io/gfile), but I am not sure if Polyaxon handles it correctly when some parts of the user code write directly to the underlying storage while others rely on the sidecar to do the syncing.

**Comment by mouradmourafiq** [comment]
Using both the sidecar and requesting the connection in the main container to be used manually should theoretically work if you do not write to the same path.

If I understand correctly, you would like to save TF outputs manually and still save `PolyaxonCallback` or `log_metrics` to log some events, if that the case it should work.
I only see one possible issue is the metadata `has_tensorboard` which gets save automatically by calling `get_tensorboard_path`, in that case you can still call that method, or manually set `log_meta(has_tensorboard=True)`.
