### ISSUE TITLE
Development setup error

### ISSUE THREAD

**Issue by akshatgit** [polyaxon/polyaxon#990]
### Unclear documentation

https://polyaxon.com/faq/how-to-contribute/

### Missing Documentation

I am finding issues while setting up a development setup. 

- First issue:
Did a `docker-compose up` got the following error:
```
Step 1/18 : FROM polyaxon-base-dev
ERROR: Service 'api' failed to build: pull access denied for polyaxon-base-dev, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
Resolved it by running: `polyaxon/cmd/rebuild/npm-base`, maybe add development guide in docs?

- Second issue: After build is complete, docker-compose up throws up the following error:
```
➜  polyaxon git:(master) docker-compose up
polyaxon_postgres_1 is up-to-date
polyaxon_redis_1 is up-to-date
Starting polyaxon_scheduler_1 ...
Starting polyaxon_api_1       ... error

Starting polyaxon_scheduler_1 ... done
se/port returned unexpected status: 500

ERROR: for api  Cannot start service api: Ports are not available: /forwards/expose/port returned unexpected status: 500
ERROR: Encountered errors while bringing up the project.
```

Let me know if this is not the recommended way of running a development version of Polyaxon.

Thanks,
Akshat

**Comment by mouradmourafiq** [comment]
Hi @akshatgit the docker-compose file is used to spin some deps for tests. You found the the commands in the github actions, which you can use to run tests as well locally. The dockerfiles and  docker-compose file ensure that anyone can run tests on their local machines without having to download or install anything.

The docker-compose is not meant to be used for `docker-compose up` or for bringing a cluster running on docker compose (it does not actually make a lot of sense since k8s is a requirement, and if you try to use the k8s config from within docker compose you will just spend a lot of time fighting with networking issues and exposing services from both sides).

Polyaxon is a quite large distributed system, there are several components that  communicate with each other in different scenarios. The [contribution guide](https://github.com/polyaxon/polyaxon/blob/master/CONTRIBUTING.md) linked in the FAQ is the way to get started if you want to contribute,  you can also the [areas](https://github.com/polyaxon/polyaxon/blob/master/CONTRIBUTING.md#areas). Please create an issue with information about what you want to achieve, the issue will be labeled with all areas that need to be updated. If you also want to contribute the changes or help with developing some parts, we will make sure to split the issues in a way to get you on-boarded.

**Comment by akshatgit** [comment]
> The docker-compose is not meant to be used for docker-compose up or for bringing a cluster running on docker-compose (it does not actually make a lot of sense since k8s is a requirement, and if you try to use the k8s config from within docker-compose you will just spend a lot of time-fighting with networking issues and exposing services from both sides).

Yes, this makes total sense. I was wondering how do you run a development instance of polyaxon while adding a new feature. I would suggest a completely isolated local microk8s so that any developer can actively develop while testing it out. 

If you are okay with it, we can further discuss it on the slack channel.

**Comment by mouradmourafiq** [comment]
> I would suggest a completely isolated local microk8s so that any developer can actively develop while testing it out.

microk8s, kind, minikube, or remote cluster all should work for the features that require access to a K8S api, e.g. the operator and the spawner. Several features can be developed without having access to a K8S api or a Polyaxon api, e.g. CLI, sdks, tracking, integrations, components, ... And actually this is how the product is developed, it's a set of libraries and modules that get installed and share some interfaces to communicate, there's no notion of setting a dev environment. 
A cluster is only required for functional tests and end to end tests, and that comes after developing the logic/feature and creating unit tests. Again some features would probably not need to have access to a cluster to ensure that they will work, for example adding a new logger for confusion matrix.

> If you are okay with it, we can further discuss it on the slack channel.

Sure feel free to ask questions. But I would suggest that you start with a small feature/enhancement until you develop more understanding of the system and then you can tackle more ambitious aspects, similar to how you would get on-boarded when you start a new job (no one will expect that you will should have a full understanding of the complete system or the ability to develop a big feature on your first couple of weeks).
